### PR TITLE
just a lil explanation

### PR DESCRIPTION
**Pull request by bloodstalker**
ditto

### CODE REVIEW

**Comment by teutsch** [comment]
This looks good!  I would just add that collaborators are encouraged to share folders as much as possible so that the project remains cohesive and we get as many eyes as possible on each contract.

**Comment by teutsch** [comment]
That makes sense.  Is there any reason why a developer *wouldn't* want to use an MIT license?

**Comment by truebitrobbie** [comment]
MIT is my vote... Thanks Farzad

**Comment by bloodstalker** [comment]
we could ask the slack channel about the licensing. sure.
for what it's worth. my opinion as a Truebit member is MIT also.

**Comment by truebitrobbie** [comment]
The whole point of this project is to build this for the community -- so anything hosted in this repo will be MIT.  It is a precondition of being part of the working group.  So just make everything MIT.  We mentioned in the slack channel and have been transparent about this from the beginning.  Lets just say MIT for everything posted here and leave it at that.

**Pull request merged**
